apiVersion: v1
kind: Pod
metadata:
  name: apache
spec:
  containers:
    - name: test-container
      image: apache      
      volumeMounts:
        - name: config-volume
          mountPoint: /etc/httpd/conf.d/
  volumes:
    - name: config-volume
      configmap: 
         name: apache
  restartPolicy: Nerver