apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-min-max-demo-lr
spec:
  limits:
  - type : Container
    max:
      cpu: "800m"
      memory: "200Mi"
    min:
      cpu: "200m"
      memory: "100Mi"
  - type : Pod
    max:
      cpu: "400m"
      memory: "400Mi"
    min:
      cpu: "100m"
      memory: "100Mi"
   