apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localPVC
spec:
  accessModes:
    - ReadWriteOne
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage