api-Version: apps/v1
kind: pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  containers:
    image: nginx
    name: pod
    resources:
        requests: 
            cpu: "200m"
            memory: "200Mi"
        limits:
            cpu: "300m"
            memory: "300Mi"