apiVersion: v1
kind: Pod
metadata:
  name: bumpy-liama
spec:
  volumes:
  - name: workdir
    emptyDir:
  containers:
  - name: checker
    image: alpine
    command: ["/bin/sh","-c", "if [-f /workdir/calm.txt];
              then sleep 1000000; else exit 1; fi"]
    volumeMounts:
    - name: workdir
      mountPath: /workdir
	  
	initContainers:
    - name: init-con
      image: alpine
      command:["/bin/sh", "-c", "touch /workdir/calm.txt"]
    volumeMounts:
    - name: workdir
      mountPath: workdir