apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: apache
    volumeMounts:
    - name: foo
      mountPath: "/etc/pki/tls/certs"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: my-cert