apiVersion: v1
kind: pod
metadata:
  name: webtool
spec:
  containers:
  - name: nginx1
    image: nginx
    env:
     - name: ProductionIP #Property Value
       valueFrom:
         configMapKeyRef:
            name: myconfig
            key: myconfig            #Get Value             
	
  
  