apiVersion: v1
kind: pod
metadata:
  name: pod1
  namespace: default
spec:
  containers:
  - name: busybox
    image: busybox:1.28
	command:
	  - sleep
	  - "3600"

   nodeName: node1.ecample.com  
		