appVersion: v1
kind: Pod
metadata:
  name: database
  lables:
	type: db
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: type
            operator: In
            values:
            - app
  containers:
     - name: nginx
       image: nginx			